FROM {{ $.source }}
LABEL maintainer="cookeem"
LABEL email="cookeem@qq.com"
RUN useradd --uid 1000 --user-group --create-home --home-dir /home/dory dory

# docker build -t {{ $.target }}{{ if $.isArm64}}-arm64v8{{ end }} -f Dockerfile-maven-{{ $.tagName }}{{ if $.isArm64}}-arm64v8{{ end }} .
