FROM {{ $.source }}
LABEL maintainer="cookeem"
LABEL email="cookeem@qq.com"
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk --update add ca-certificates git curl zip jq tree htop bash && \
    update-ca-certificates && \
    rm -rf /var/cache/apk/*

# docker build -t {{ $.target }}{{ if $.isArm64}}-arm64v8{{ end }} -f Dockerfile-alpine-{{ $.tagName }}{{ if $.isArm64}}-arm64v8{{ end }} .
