FROM {{ $.source }}
LABEL maintainer="cookeem"
LABEL email="cookeem@qq.com"
RUN adduser -u 1000 -D dory && \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk --update add ca-certificates curl gcc musl-dev git zip jq tree htop && \
    update-ca-certificates

# docker build -t {{ $.target }}{{ if $.isArm64}}-arm64v8{{ end }} -f Dockerfile-python-{{ $.tagName }}{{ if $.isArm64}}-arm64v8{{ end }} .
