---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: project-data-pod
  name: project-data-pod
  namespace: {{ $.dory.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-data-pod
  serviceName: project-data-pod
  template:
    metadata:
      labels:
        app: project-data-pod
    spec:
      containers:
        - command:
            - cat
          tty: true
          image: {{ if eq $.dory.imageRepo.type "harbor" }}{{ $.imageRepoDomainName }}/public/{{ else }}doryengine/{{ end }}alpine:3.17.2-dory
          imagePullPolicy: IfNotPresent
          name: project-data-pod
          volumeMounts:
            - mountPath: /etc/timezone
              name: configmap-timezone
              readOnly: true
              subPath: timezone
            - mountPath: /etc/localtime
              name: zoneinfo
              readOnly: true
              subPath: {{ $.kubernetes.timezone }}
            - mountPath: /usr/share/zoneinfo
              name: zoneinfo
              readOnly: true
            - mountPath: /project-data
              name: project-data-pvc
              subPath: .
          env:
            - name: TZ
              value: {{ $.kubernetes.timezone }}
      {{- if eq $.dory.imageRepo.type "harbor" }}
      imagePullSecrets:
        - name: {{ $.imageRepoDomainName }}
      {{- end }}
      volumes:
        - name: configmap-timezone
          configMap:
            name: configmap-timezone
            items:
              - key: timezone
                path: timezone
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
            type: Directory
        - name: project-data-pvc
          persistentVolumeClaim:
            claimName: project-data-pvc
