version: '3'
services:
  nginx-lb:
    image: {{ $.nginxlbImage }}
    container_name: nginx-lb
    hostname: nginx-lb
    volumes:
      - ./nginx-lb.conf:/etc/nginx/nginx.conf
    network_mode: host
    restart: always
